### ISSUE TITLE
background-image from "body > div" also ruler

### ISSUE THREAD

**Issue by dwengs** [Esteban-Rocha/page-ruler-redux#26]
If a web page has this kind of css:
```css
body > div {
  background-image: url(...);
}
````
Ruler uses this background-image for its background since its also a direct child of body.
a simple
```css
#page-ruler {
  background-image: none;
}
````
seems to solve this problem.
